/*
 * Сервис баннеров
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package types

type BannerPostRequest struct {

	// Идентификаторы тэгов
	TagIds []int `json:"tag_ids,omitempty"`

	// Идентификатор фичи
	FeatureId int `json:"feature_id,omitempty"`

	// Содержимое баннера
	Content map[string]interface{} `json:"content,omitempty"`

	// Флаг активности баннера
	IsActive bool `json:"is_active,omitempty"`
}

// AssertBannerPostRequestRequired checks if the required fields are not zero-ed
func AssertBannerPostRequestRequired(obj BannerPostRequest) error {
	return nil
}

// AssertBannerPostRequestConstraints checks if the values respects the defined constraints
func AssertBannerPostRequestConstraints(obj BannerPostRequest) error {
	return nil
}
