/*
 * Сервис баннеров
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package types

import (
	"time"
)

type BannerGet200ResponseInner struct {
	// Идентификатор баннера
	BannerId int `json:"banner_id,omitempty"`
	// Идентификаторы тэгов
	TagIds []int `json:"tag_ids,omitempty"`
	// Идентификатор фичи
	FeatureId int `json:"feature_id,omitempty"`
	// Содержимое баннера
	Content map[string]interface{} `json:"content,omitempty"`
	// Флаг активности баннера
	IsActive bool `json:"is_active,omitempty"`
	// Дата создания баннера
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Дата обновления баннера
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertBannerGet200ResponseInnerRequired checks if the required fields are not zero-ed
func AssertBannerGet200ResponseInnerRequired(obj BannerGet200ResponseInner) error {
	return nil
}

// AssertBannerGet200ResponseInnerConstraints checks if the values respects the defined constraints
func AssertBannerGet200ResponseInnerConstraints(obj BannerGet200ResponseInner) error {
	return nil
}
